services:
  postgres:
    image: postgres:16-alpine
    container_name: mini-quiz-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: miniquiz
      POSTGRES_PASSWORD: miniquiz
      POSTGRES_DB: miniquiz
    ports:
      - "5432:5432"
    volumes:
      - mini-quiz-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniquiz", "-d", "miniquiz"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:8.2-alpine
    container_name: mini-quiz-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--save", ""]
    volumes:
      - mini-quiz-redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  nats:
    image: nats:2.14.0-alpine
    container_name: mini-quiz-nats
    restart: unless-stopped
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - mini-quiz-natsdata:/data
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mini-quiz-pgdata:
  mini-quiz-redisdata:
  mini-quiz-natsdata:
