apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts
    targetRevision: 2.14.0
    helm:
      releaseName: nats
      values: |
        config:
          jetstream:
            enabled: true
            fileStore:
              enabled: true
              pvc:
                enabled: true
                size: 10Gi
                storageClassName: do-block-storage
          monitor:
            enabled: true
        container:
          resources:
            requests: { cpu: 200m, memory: 384Mi }
            limits:   { memory: 768Mi }
        promExporter:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
