apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-payloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/viralsangani/mini-quiz
    targetRevision: main
    path: deploy/manifests/sealed-secrets
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: bitnami.com
      kind: SealedSecret
      jsonPointers: [/metadata/creationTimestamp]
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
