---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miniquiz-pg-app
  namespace: api
spec:
  encryptedData:
    password: AgCM/b4Z8mzCUDxvPJ88ALaCy9rY9SL88dENSklfm+RPVDXRbmeyRo+D/7Aadkv1zAjEIFKmih2VgdmcfvbSMBd81raOyYB4tnhk4Wk06BcIJ8xeKbfLwX8UdvXjX6TIGgJUlZaA8HoItpNaP7gPi9uZTkeDV2PamfvPbZJDhk7NeNPeM570FAboFB8vM0FWXUlumKn2ds4mM8hZ/NN6rfwRW1WGBMBv+/vSKBTBAQIxNLZxwLjneieh0GS4kTdXbypy6dCB15SjjIzfXC56E21OsoJEH2QVzuQuJ72/TGY1cz69ll88c4QrKIxv7dYDcltY/uDrqE4O7S9F6U/XLh0eIbX4f/kUXem7uVVXwSpRw72SMwYrO582xtOn+gdmiLyzkA8k5ib9NyAEu03B1hIKlHBpbEOspr2ZSsyTjdK4hyGa49oFstphr5A1sS1wTVuVt9wEUoWpqt/NR1osUOueAFYuc58tYZHo/JXN6JxwGLxzGGGpDU5dxRJquOchuYx+MpU7STub0hFfq/IlYq0PhGAI9x2C9RsXegp9NDMrP12NgbjvmOb3lXxvgIkuKgeLM0IkkgWi+dNxinGcXyHMa8XXlNnXj3bcWUnIFkWilwtfE8heYd7+e9MPXh/jB+CQU8FM5HnQlpi7ouvsaac4m1ZtxAAhmDz8Kl30ywTZeL5hivEB50u/yPhxcgkHWzz6kJu+agPwpK4KjniM9KwFULLsewmmZzvy3T2oEsgOS1Jql8tJbptdhZw8VuMjM4F00lUu1FbWs+g/aPfWPCRE
    username: AgA8E3O58WQ9A4alO0kfBFx4fON5aL0/FqewFwZ4SE+azG4NwL70OVCoblkyQYLJB/Yn0TBOiUSTbdWOXGxHuG/2zSjj91IuZSjGGkGrMr6l/Ut/QhBiZFfO8ZrYwkamwGwyuAMsLAd/Ctho8XocuVd8QFAURF9ymg+iRuqhobLJoIddgFxV4E2taDHLtaABSmOmWqbf7GIsDQe6ddeMHpipR5g68CGg2VH1+cOtb44ngowvVV0e+8aaNtHQ25AXuwKwBRCelepbtoEWHQmtd9YjoBYGT4jfaNiPYuPpLZQWF3r5Wb8r8BJhto4VU9n+LcWQGDiUKuAgnw7Exvac7h6AqP1UbDVmqXDbr7sNGTm8AUYqmH3vN+A8JSl+6hprNEvaIqpt4ji0XsfNmTrsbNc4RrJp5zOzfjw3CaenLZOc3tA/929YMJSAEhN8BqSPfhEtFMrErbyQG3KGVhccLY7o+j7ESTph2tzhZfDTi+pMhW3hDY1X93EwGuufGxpXnD2RuvrqonuVEM+On7H/T63a5QLUVe3yt5FFkvxXmK+078M3emgHdzXJ7YUMOo88acm6iDi5J1DFMmKMaz/X9CaUZL8ho6sWmxPaCXEHEUMgDpByoFFCn2KLpfYUQo9+UJ61tRPuTurcxNJWbuh0bASVnGBwAcBrgQ1okVWdkOC2k4HlQlUvHdRKKi8O98J2Oe1aCpoOY8JW8w==
  template:
    metadata:
      name: miniquiz-pg-app
      namespace: api
    type: Opaque
