apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "api.fullname" . }}-migrate-{{ .Values.image.tag | replace "." "-" | trunc 20 }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
        job: migrate
    spec:
      restartPolicy: Never
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -lc
            - "node_modules/.bin/prisma migrate deploy"
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.postgresSecret }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.postgresSecret }}
                  key: password
            - name: DATABASE_URL
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@{{ .Values.postgres.service }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits:   { memory: 256Mi }
